//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DreamOfLiving_Spaces_MvcWeb.DB_model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApartmentAd
    {
        public int Id { get; set; }
    }
}
