//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DreamOfLiving_Spaces_MvcWeb.DB_model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBModelContainer : DbContext
    {
        public DBModelContainer()
            : base("name=DBModelContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<User> UserSet { get; set; }
        public virtual DbSet<ApartmentAd> ApartmentAdSet { get; set; }
        public virtual DbSet<Trade> TradeSet { get; set; }
        public virtual DbSet<ApAdConnectedInTrade> ApAdConnectedInTradeSet { get; set; }
        public virtual DbSet<ContactInfo> ContactInfoSet { get; set; }
        public virtual DbSet<ApartmentDemand> ApartmentDemandSet { get; set; }
    }
}
